"""@brief Module for handling lexicon data."""

from typing import List

import random

__names: dict = {
        'Abizur': None,
        'Agariastan': None,
        'Agatonia': None,
        'Agralva': None,
        'Akbancet': None,
        'Alchi': None,
        'Altaged': None,
        'Anaria': None,
        'Anbrya': None,
        'Andgre Nyamana': None,
        'Andie': None,
        'Andnew Tolyzer': None,
        'Andura': None,
        'Ansalia': None,
        'Aquaray': None,
        'Ardignola': None,
        'Artea': None,
        'Augustem': None,
        'Aulando': None,
        'Auran': None,
        'Ava Gasrea': None,
        'Awaciva': None,
        'Bai': None,
        'Baldives': None,
        'Bartic Rkmebon': None,
        'Bathernbia': None,
        'Begristia': None,
        'Bellostria': None,
        'Belspear': None,
        'Belthria': None,
        'Benjiet': None,
        'Biachiandistan': None,
        'Bianei': None,
        'Bianiani': None,
        'Bleson': None,
        'Blicnangobarcao': None,
        'Bonia': None,
        'Braipabali': None,
        'Brousellia': None,
        'Caiquatapitma': None,
        'Calravia': None,
        'Calvacros': None,
        'Caocoba': None,
        'Cargo': None,
        'Carocmaclize': None,
        'Caydaia': None,
        'Ciaca Zapiala': None,
        'Cognoscenti': None,
        'Colgadur': None,
        'Corize': None,
        'Corvalon': None,
        'Cyneil': None,
        'Cyrvenon': None,
        'Dantser Landta': None,
        'Datu': None,
        'Desheria': None,
        'Dinkapu': None,
        'Djauntrie': None,
        'Domnua Canle': None,
        'Dorboslo': None,
        'Dynalis': None,
        'Earina': None,
        'Eastern Pena Rianiaba': None,
        'Elandezia': None,
        'Elandrew': None,
        'Elthia': None,
        'Emperoa': None,
        'Eradonya': None,
        'Erriador': None,
        'Esteron': None,
        'Eucon': None,
        'Farelo': None,
        'Filandria': None,
        'Fyernak': None,
        'Galinah': None,
        'Galvansha': None,
        'Genorah': None,
        'Gesalsia': None,
        'Glacanon': None,
        'Glacolia': None,
        'Glorosa': None,
        'Greecetu': None,
        'Grezamba': None,
        'Guarirwanbe': None,
        'Guayof Elchrist': None,
        'Guernri': None,
        'Gyptblicanda': None,
        'Hongnenitedlasey': None,
        'Iau': None,
        'Ibudron': None,
        'Icarus': None,
        'Ime Gakhstanbe': None,
        'Imnalia': None,
        'Innau': None,
        'Isandticlifi': None,
        'Isierria': None,
        'Isteros': None,
        'Isu Zijo': None,
        'Ivritea': None,
        'Jarluke': None,
        'Jenanat': None,
        'Jordanus': None,
        'Jufitz': None,
        'Kairana': None,
        'Kalexa': None,
        'Karderville': None,
        'Khramos': None,
        'Kiaque': None,
        'Klantak': None,
        'Klihan': None,
        'Korrinius': None,
        'Krila': None,
        'Krusada': None,
        'Lamo Groborat': None,
        'Landchten Laumai': None,
        'Landniakitts': None,
        'Lasiacos': None,
        'Layrytubebang': None,
        'Leili': None,
        'Lela': None,
        'Lethepa': None,
        'Lipcame': None,
        'Livonshire': None,
        'Lorrenvia': None,
        'Loryntia': None,
        'Loupebourg Thoco': None,
        'Lunabria': None,
        'Lunalirsey': None,
        'Lunamor': None,
        'Mabhui': None,
        'Madanell': None,
        'Maniasaint': None,
        'Manstan': None,
        'Marrial Rymahong': None,
        'Marru Tiapua': None,
        'Masve Zepitdian': None,
        'Mauthe Guatiti': None,
        'Menruser': None,
        'Merthal': None,
        'Mikraine Rimarle': None,
        'Milo Monya': None,
        'Mirenze': None,
        'Mitanor': None,
        'Mocoslands': None,
        'Mode Latari': None,
        'Modestria': None,
        'Monefri': None,
        'Monor': None,
        'Morasta': None,
        'Myanceanuslands': None,
        'Myzellon': None,
        'Nablic Stanvata': None,
        'Nakka': None,
        'Namkrainemar': None,
        'Narea': None,
        'Naurra': None,
        'Ncentsaintma': None,
        'Neacay Ranmophi': None,
        'Neardan': None,
        'Neathua Guioof': None,
        'Negium': None,
        'Nemar': None,
        'Nentilla': None,
        'Nervontia': None,
        'Neva Efe': None,
        'Nevisci': None,
        'Ngoanthio': None,
        'Nilaturkscook': None,
        'Ninnairebripri': None,
        'Noresta': None,
        'Norry Hrainba': None,
        'Novuron': None,
        'Ntima Alsauna': None,
        'Ocasta': None,
        'Ogatheon': None,
        'Ojekki': None,
        'Olesea': None,
        'Olyndria': None,
        'Pacidia': None,
        'Pariston': None,
        'Paso': None,
        'Pierredo Mica': None,
        'Porejimo': None,
        'Poresaint': None,
        'Prenata': None,
        'Prusslo Tosouthma': None,
        'Pury Straa': None,
        'Quioni': None,
        'Rare': None,
        'Rarea Ncipethai': None,
        'Rdanland': None,
        'Reakireuje': None,
        'Recogui': None,
        'Remon': None,
        'Rene Xibue': None,
        'Resoland': None,
        'Reu Leoneuguam': None,
        'Roseliand': None,
        'Roulamonte': None,
        'Rozinya': None,
        'Rusmo': None,
        'Ruszilda': None,
        'Saintar Boan': None,
        'Saintcook Sanorsia': None,
        'Saintdia Stansia': None,
        'Sainttar': None,
        'Salarenias': None,
        'Salaria': None,
        'Salmaca': None,
        'Salterra': None,
        'Secanrateslandpu': None,
        'Skalacion': None,
        'Slandroc': None,
        'Slandsof': None,
        'Slandsra': None,
        'Slandsribard': None,
        'Sormbay': None,
        'Soroonratesdai': None,
        'Sostrafusigo': None,
        'Stangregaostan': None,
        'Statestile': None,
        'Stomaua': None,
        'Stragenesia': None,
        'Stranamor': None,
        'Sui Amoa': None,
        'Sujanco': None,
        'Sunmede': None,
        'Swinited Verosstates': None,
        'Tachelles Lapo': None,
        'Talzania': None,
        'Tanaxes': None,
        'Tanintelom': None,
        'Tardu Tishmogeor': None,
        'Thernmi Sriau': None,
        'Thettene': None,
        'Toa Stannonor': None,
        'Trevinia': None,
        'Trumpington': None,
        'Tukoqua': None,
        'Tulis': None,
        'Tybrell': None,
        'Uther': None,
        'Vahrenhall': None,
        'Valanthea': None,
        'Valtano': None,
        'Ventamonte': None,
        'Ventus': None,
        'Vespinara': None,
        'Vilcania': None,
        'Virlu': None,
        'Vobia': None,
        'Wyngarria': None,
        'Xaveland': None,
        'Xentael': None,
        'Xollara': None,
        'Zamro Ufunor': None,
        'Zaraerune': None,
        'Zathetia': None,
    }

def assign(name: str, obj: object) -> bool:
    """Assign an object to a lexicon entry by name."""
    if name not in __names:
        print(f"Name '{name}' not found in lexicon.")
        confirm: str = input(f"Add '{name}' to lexicon? [Yes/No]: ")
        if confirm.lower()[0] == 'y':
            __names[name] = obj
            print(f"Added '{name}' to lexicon.")
            return True
        else:
            print(f"Did not add '{name}' to lexicon.")
            return False
    else:
        __names[name] = obj
        return True


def is_used(name: str) -> bool:
    """Check if a lexicon entry is already assigned."""
    return name in __names and __names[name] is not None


def random_unused() -> str|None:
    """Select a random, unused lexicon entry."""
    available_names: List = [k for k, v in __names.items() if v is None]
    return random.choice(available_names) if 0 < len(available_names) else None


def select(name: str) -> object:
    """Select a lexicon entry by name."""
    return __names[name] if name in __names else None
